from pydantic import BaseModel, Field
from typing import List
from langchain_tavily import TavilySearch
from langchain.agents import create_agent
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv

load_dotenv()


class Source(BaseModel):
    """Represents a source of information for the agent's response."""

    name: str = Field(
        description="The name of the source, e.g., 'Wikipedia', 'News Article', etc."
    )
    url: str = Field(description="The URL of the source for reference.")
    relevance_score: float = Field(
        description="A score indicating the relevance of this source to the query, on a scale from 0 to 1."
    )


class AgentResponse(BaseModel):
    """Represents the structured response from the agent."""

    answer: str = Field(
        description="The main answer generated by the agent in response to the query."
    )
    sources: List[Source] = Field(
        description="A list of sources that the agent used to generate its answer, along with relevance scores."
    )


# Lesson 3
def main():
    print("Hello from real search tool!")

    # 1. Initialize the LLM
    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

    # 2. Initialize the pre-built tool
    search = TavilySearch(max_results=2)
    tools = [search]

    # 3. Create the Agent
    agent = create_agent(
        llm,
        tools,
        system_prompt="You are a helpful assistant that uses the search tool to answer questions using the internet, ummarize the results.",
        response_format=AgentResponse,
    )

    # 4. Invoke the Agent
    inputs = {"messages": [
        ("user", "What is the latest news regarding SpaceX today?")]}

    print("Agent is thinking and searching the web...")
    result = agent.invoke(inputs)

    # 5. Print the final message from the conversation
    final_message = result["messages"][-1]

    content = final_message.content
    # Clean up output if Gemini returns a list of blocks
    if isinstance(content, list):
        text_parts = [
            part["text"]
            for part in content
            if isinstance(part, dict) and "text" in part
        ]
        content = " ".join(text_parts) if text_parts else str(content)

    print("\nFinal Answer:\n", content)


if __name__ == "__main__":
    main()
