import os
from typing import List, Dict, Any
from langchain.agents import create_agent
from langchain.chat_models import init_chat_model
from langchain.messages import ToolMessage
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_pinecone import PineconeVectorStore
from langchain.tools import tool
load_dotenv()

EMBEDDING_MODEL = "models/gemini-embedding-2"
embeddings = GoogleGenerativeAIEmbeddings(model=EMBEDDING_MODEL,
                                          output_dimensionality=1536)
llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")

vectorstore = PineconeVectorStore(index_name=os.environ.get(
    "PINECONE_INDEX_NAME"), embedding=embeddings, namespace="langchain-docs")

model = init_chat_model(
    model="gemini-2.0-flash",
    model_provider="google_genai"
)


@tool(response_format="content_and_artifact")
def retrieve_context(query: str):
    """Retrieve relevant documentation chunks from Pinecone based on the query about LangChain"""

    # Retrieve top 4 documents

    retrieved_docs = vectorstore.as_retriever().invoke(query, k=4)

    # Sereialize documents for model
    serialized_docs = "\n\n".join(
        (f"Source: {doc.metadata.get('source', 'Unknown')}\nContent: {doc.page_content}")
        for doc in retrieved_docs

    )

    return serialized_docs, retrieved_docs


def run_llm(query: str) -> Dict[str, Any]:
    """Run the RAG Pipeline with the given query and return the response along with any retrieved context artifacts.
    Args:
        query (str): The user's question or query about LangChain documentation.

    Returns:
        Dictionary Containing:
        - answer: The answer generated by the LLM.
        - context: List of retrieved documents that were used as context for generating the answer.

    """

    # create the agent with the LLM and the retrieval tool
    system_prompt = (
        "You are an expert assistant specializing in LangChain documentation."
        "Use the provided context to answer the user's question in details."
        "You have access to the tool that retrieves relevant documentation chunks based on the user's query. "
        "Always cite the tools you use to retrieve information. If the answer isn't explicitly in the context but the context gives clues, use those clues to infer the answer."
        "If you can not find the answer in the context, say you don't know instead of making up an answer."
    )

    agent = create_agent(
        model,
        tools=[retrieve_context],
        system_prompt=system_prompt
    )

    # build message list
    messages = [{"role": "user", "content": query}]

    # invoke the agent with the query
    response = agent.invoke({"messages": messages})

    # Extract the last answer from the response
    answer = response["messages"][-1].content

    # Extract the context documents
    context_docs = []
    for message in response["messages"]:
        # check if this is a ToolMessage with artifact
        if isinstance(message, ToolMessage) and hasattr(messages, "artifact"):
            # The artifact should contain list of Document Objects
            if isinstance(message, List):
                context_docs.extend(message.artifact)

    return {
        "answer": answer,
        "context": context_docs
    }


if __name__ == '__main__':
    result = run_llm(query="what are deep agents?")
    print(result)
